import { type Actor } from '../domain/entities.ts'
import {
  isNotifiableEvent,
  type Notification,
  type NotificationView,
} from '../domain/notifications.ts'
import { type TransactionContext, type UnitOfWork } from '../ports/repositories.ts'
import { type Clock, type IdGenerator } from '../ports/runtime.ts'

export interface NotificationServiceDeps {
  uow: UnitOfWork
  clock: Clock
  ids: IdGenerator
}

/** The default inbox page — dwarfs any real unread backlog for a small team. */
const DEFAULT_LIST_LIMIT = 50

/**
 * In-app notifications (docs/architecture/notifications.md). Notifications are
 * generated by fanning a committed card event out to the card's WATCHERS,
 * excluding the actor (you never notify yourself). Reads are scoped to the
 * recipient — a user only ever sees or marks their own.
 */
export class NotificationService {
  private readonly deps: NotificationServiceDeps

  constructor(deps: NotificationServiceDeps) {
    this.deps = deps
  }

  /**
   * Fans a COMMITTED card event out to the card's watchers (except the actor).
   * Best-effort and post-commit — a failure here never undoes the mutation that
   * already happened. Non-notifiable events (a reorder, a PII redaction, comment
   * edits/deletes) produce nothing. Returns the recipient ids so the caller can
   * target real-time delivery.
   */
  async fanOutForEvent(cardId: number, eventId: string): Promise<string[]> {
    return this.deps.uow.run(async (tx) => {
      const event = await tx.events.findById(eventId)
      if (event === null || !isNotifiableEvent(event.eventType)) return []
      const watchers = await tx.cardWatchers.listWatcherIds(cardId)
      const recipients = watchers.filter((id) => id !== event.actorId)
      const nowIso = this.deps.clock.now().toISOString()
      for (const userId of recipients) {
        const notification: Notification = {
          id: this.deps.ids.newId(),
          userId,
          cardId,
          actorId: event.actorId,
          eventType: event.eventType,
          createdAt: nowIso,
          readAt: null,
        }
        await tx.notifications.insert(notification)
      }
      return recipients
    })
  }

  /** The acting user's inbox, newest-first, each resolved to card title + actor name. */
  async list(
    actor: Actor,
    options: { limit?: number; unreadOnly?: boolean } = {},
  ): Promise<NotificationView[]> {
    return this.deps.uow.read(async (tx) => {
      const rows = await tx.notifications.listForUser(actor.id, {
        limit: options.limit ?? DEFAULT_LIST_LIMIT,
        ...(options.unreadOnly !== undefined ? { unreadOnly: options.unreadOnly } : {}),
      })
      const views: NotificationView[] = []
      for (const row of rows) views.push(await this.toView(tx, row))
      return views
    })
  }

  /** The acting user's unread count (the bell badge). */
  async unreadCount(actor: Actor): Promise<number> {
    return this.deps.uow.read((tx) => tx.notifications.unreadCount(actor.id))
  }

  /** Marks one of the caller's notifications read (no-op if not theirs / already read). */
  async markRead(actor: Actor, id: string): Promise<void> {
    await this.deps.uow.run((tx) =>
      tx.notifications.markRead(id, actor.id, this.deps.clock.now().toISOString()),
    )
  }

  /** Marks every unread notification of the caller read; returns the count affected. */
  async markAllRead(actor: Actor): Promise<number> {
    return this.deps.uow.run((tx) =>
      tx.notifications.markAllRead(actor.id, this.deps.clock.now().toISOString()),
    )
  }

  /** Resolves a stored row to its inbox view (card title + actor display name). */
  private async toView(tx: TransactionContext, row: Notification): Promise<NotificationView> {
    const card = await tx.cards.findById(row.cardId)
    // actorId may be a user id (resolved) or a service-token id (not a user → null).
    const actor = row.actorId === null ? null : await tx.users.findById(row.actorId)
    return {
      id: row.id,
      cardId: row.cardId,
      cardTitle: card?.title ?? '',
      eventType: row.eventType,
      actorName: actor?.displayName ?? null,
      createdAt: row.createdAt,
      read: row.readAt !== null,
    }
  }
}
